[package]
name = "rozen"
version = "0.1.0"
authors = ["Anja Berens <pharaun666@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# FS Walker
ignore = "0.4"

# Compressor
zstd = "0.9"

# Hasher
blake3 = "1.0.0"

# Encryption
sodiumoxide = "0.2.7"

# File Index
rusqlite = { version = "0.25.3", features = ["bundled"] }
tempfile = "3"

# Time library
time = { version = "0.3.7", features = ["formatting"] }

# Configuration
toml = "0.5"

# Serialization
serde = { version = "1.0", features = ["derive"] }
bincode = "1.1.3"

# VFS layer for in memory and later on-disk VFS backend
vfs = "0.5.1"

# Error layer for handling error creation
thiserror = "1.0"

# S3 layer for the backend
aws-config = "0.6.0"
aws-sdk-s3 = "0.6.0"
tokio = { version = "1", features = ["full"] }
http = "*"
bytes = "*"
