[package]
name = "rozen"
version = "0.1.0"
authors = ["Anja Berens <pharaun666@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
copy-test = []

[dependencies]

# FS Walker
ignore = "0.4"

# Compressor
zstd = "0.9"

# Hasher
blake3 = "1.0.0"

# Encryption
sodiumoxide = "0.2.7"

# File Index
rusqlite = { version = "0.25.3", features = ["bundled"] }
tempfile = "3"

# Configuration
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }

# VFS layer for in memory and later on-disk VFS backend
vfs = "0.5.1"
