[package]
name = "rozen"
version = "0.1.0"
authors = ["Anja Berens <pharaun666@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# FS Walker
ignore = "0.4"

# Compressor
zstd = "0.9"

# Index
rusqlite = { version = "0.25.3", features = ["bundled"] }

# Temporary hash to prove some concepts
crypto-hash = "0.3.4"

# Temporary archive format
zip = "0.5.13"
